name = "Entities"
uuid = "1768915e-f209-48c3-8e70-04c8c5555943"
authors = ["Cédric BELMANT"]
version = "0.0.1"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
